### ISSUE TITLE
Add US West/East indicators to world icons

### ISSUE THREAD

**Issue by burkeg** [jcarbelbide/tog-crowdsourcing#11]
Add US West/East indicators to world icons

**Comment by jcarbelbide** [comment]
Thanks for the suggestion!

I don't think that Jagex exposes where the servers are located, do they? I don't remember seeing anything where the US servers distinguished between east/west servers. Additionally, there are a lot of players that are not in the US, so this feature wouldn't help them too much. 

This problem I think would be better solved by adding a ping column, what do you think? That feature has been requested a couple of times. I had a change to add that feature but unfortunately there were some problems when trying to add it to the live plugin that I haven't gotten around to fixing. My time to work on this is pretty limited unfortunately due to work, but if there is a lot of support for that, I'll try to find time to work on it.

Closing this issue, as I believe the ping feature would be a better fit and there is already an open issue on it. Thank you again for the idea!

**Comment by burkeg** [comment]
It is publicly available, in a recent game update the in-game world switcher icons show an arrow indicating East/West Coast. The wiki page has the exact list https://oldschool.runescape.wiki/w/Server

**Comment by jcarbelbide** [comment]
Interesting, thanks! Do you know if the world switcher runelite plugin has also been updated to use the new East/West Coast icons? The ToG plugin is actually just recycling the icons and code from the world switcher plugin, so if thats been updated, I bet I'd just have to bump the version on this plugin to get it working

**Comment by burkeg** [comment]
It does not unfortunately, I'll go bug them 😉

**Comment by burkeg** [comment]
Howdy I wanted to ping here because the world hopper plugin has been updated after me bugging them :)

**Comment by jcarbelbide** [comment]
haha nice, let me check to see if its easy to add these icons. Thanks for the follow up!

**Comment by jcarbelbide** [comment]
https://github.com/jcarbelbide/tog-crowdsourcing/pull/14

**Comment by jcarbelbide** [comment]
related on runelite repo:
https://github.com/runelite/runelite/pull/17306

**Comment by jcarbelbide** [comment]
This should be live. Closing.

**Comment by ingmarins** [comment]
<img width="232" height="75" alt="Image" src="https://github.com/user-attachments/assets/f32d3b6f-6373-42d7-af3b-9f6881dc631d" />

<img width="231" height="184" alt="Image" src="https://github.com/user-attachments/assets/edc45730-358a-4d4f-b39f-445acfa1f71b" />

 661 (Singapore) missing regional indicator, as do some other worlds. Seems to be missing not just the newest expansion wave (South Africa, Japan, Singapore) but even Brazil which was added prior. World hopper plugin has these indicators already.
